"""
Core module for CRMS backend.
Provides configuration, constants, exceptions, and base classes.
"""

from .base import (
    BaseClassifier,
    BaseExtractor,
    BasePlugin,
    BaseProcessor,
    BaseResult,
    BaseValidator,
)
from .config import (
    AnalyticsConfig,
    CacheConfig,
    ClassificationConfig,
    DatabaseConfig,
    FileProcessingConfig,
    IPCConfig,
    JobQueueConfig,
    LoggingConfig,
    OCRConfig,
    PerformanceConfig,
    ReorganizationConfig,
    Settings,
    get_settings,
    settings,
)
from .constants import (
    CONFIDENCE_HIGH,
    CONFIDENCE_LOW,
    CONFIDENCE_MEDIUM,
    CONFIDENCE_MINIMAL,
    ChangeType,
    DocumentStatus,
    DocumentType,
    ExtractionMethod,
    FileExtension,
    RelationshipType,
    SequenceType,
    ValidationType,
)
from .exceptions import (
    AnalyticsError,
    ClassificationError,
    ConfigurationError,
    CRMSException,
    DatabaseError,
    DocumentNotFoundError,
    FileProcessingError,
    IPCError,
    JobQueueError,
    MetadataExtractionError,
    OCRError,
    PluginError,
    ReorganizationError,
    ReportGenerationError,
    SearchError,
    UndoError,
    ValidationError,
)
from .logging import get_logger, setup_logging

__all__ = [
    # Configuration
    "Settings",
    "get_settings",
    "settings",
    "DatabaseConfig",
    "IPCConfig",
    "OCRConfig",
    "FileProcessingConfig",
    "ClassificationConfig",
    "ReorganizationConfig",
    "LoggingConfig",
    "CacheConfig",
    "PerformanceConfig",
    "JobQueueConfig",
    "AnalyticsConfig",
    # Constants
    "DocumentType",
    "FileExtension",
    "ChangeType",
    "RelationshipType",
    "ValidationType",
    "SequenceType",
    "DocumentStatus",
    "ExtractionMethod",
    "CONFIDENCE_HIGH",
    "CONFIDENCE_MEDIUM",
    "CONFIDENCE_LOW",
    "CONFIDENCE_MINIMAL",
    # Exceptions
    "CRMSException",
    "ConfigurationError",
    "DatabaseError",
    "FileProcessingError",
    "DocumentNotFoundError",
    "MetadataExtractionError",
    "OCRError",
    "ClassificationError",
    "ValidationError",
    "ReorganizationError",
    "UndoError",
    "SearchError",
    "ReportGenerationError",
    "IPCError",
    "PluginError",
    "JobQueueError",
    "AnalyticsError",
    # Base classes
    "BaseResult",
    "BaseExtractor",
    "BaseClassifier",
    "BaseValidator",
    "BasePlugin",
    "BaseProcessor",
    # Logging
    "setup_logging",
    "get_logger",
]
